version: '3.8'

services:
  postgres:
    image: postgres
    container_name: backEndTest
    environment:
      POSTGRES_USER: userTest
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: bd_test_pg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: